version: "3.8"

services:
  orchestration:
    image: camunda/camunda:${CAMUNDA_VERSION:-8.8.0}
    container_name: camunda-orchestration
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    ports:
      - "8080:8080"
    depends_on:
      - connectors
      - optimize
      - identity
      - console
      - keycloak
      - elasticsearch
      - postgres

  connectors:
    image: camunda/connectors-bundle:${CAMUNDA_CONNECTORS_VERSION:-8.8.0}
    container_name: camunda-connectors
    environment:
      - CONNECTORS_LOG_LEVEL=INFO
    ports:
      - "8081:8080"

  identity:
    image: camunda/identity:${CAMUNDA_IDENTITY_VERSION:-8.8.0}
    container_name: camunda-identity
    environment:
      - IDENTITY_LOG_LEVEL=INFO
    ports:
      - "8082:8080"

  optimize:
    image: camunda/optimize:${CAMUNDA_OPTIMIZE_VERSION:-8.8.0}
    container_name: camunda-optimize
    environment:
      - OPTIMIZE_ELASTICSEARCH_HOST=elasticsearch
      - OPTIMIZE_ELASTICSEARCH_PORT=9200
    ports:
      - "8083:8080"
    depends_on:
      - elasticsearch

  web-modeler-restapi:
    image: camunda/web-modeler-restapi:${CAMUNDA_WEB_MODELER_VERSION:-8.8.0}
    container_name: camunda-web-modeler-restapi
    environment:
      - WEB_MODELER_DB_HOST=web-modeler-db
      - WEB_MODELER_DB_PORT=5432
    ports:
      - "8084:8080"
    depends_on:
      - web-modeler-db

  console:
    image: camunda/console:${CAMUNDA_CONSOLE_VERSION:-8.8.7}
    container_name: camunda-console
    environment:
      - CONSOLE_LOG_LEVEL=INFO
    ports:
      - "8085:8080"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION:-8.17.5}
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"

  keycloak:
    image: bitnamilegacy/keycloak:${KEYCLOAK_SERVER_VERSION:-26.3.2}
    container_name: keycloak
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_IMPORT=/opt/keycloak/import/realm-export.json
    ports:
      - "8086:8080"

  mailpit:
    image: axllent/mailpit:${MAILPIT_VERSION:-v1.21.8}
    container_name: mailpit
    ports:
      - "8025:8025"

  postgres:
    image: postgres:${POSTGRES_VERSION:-15-alpine3.22}
    container_name: postgres
    environment:
      - POSTGRES_USER=camunda
      - POSTGRES_PASSWORD=camunda
      - POSTGRES_DB=camunda
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  web-modeler-db:
    image: postgres:${POSTGRES_VERSION:-15-alpine3.22}
    container_name: web-modeler-db
    environment:
      - POSTGRES_USER=webmodeler
      - POSTGRES_PASSWORD=webmodeler
      - POSTGRES_DB=webmodeler
    volumes:
      - webmodeler-data:/var/lib/postgresql/data

volumes:
  postgres-data:
  webmodeler-data:
